---
# tasks file for ansible-role-terragrunt

- name: Include OS specific variables.
  ansible.builtin.include_vars: "{{ ansible_system }}.yml"

- name: Install Terragrunt
  ansible.builtin.include_tasks: "setup-{{ ansible_system }}.yml"
