---
# tasks file for install terragrunt on Linux system

- name: Linux | Get the latest published full release for the repository
  uri:
    url: https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest
    return_content: yes
  register: terragrunt_index
  check_mode: no
  when: terragrunt_version == "latest"

- name: Linux | Filter the latest Terragrunt version
  set_fact:
    terragrunt_version_to_install: "{{ (terragrunt_index.content | from_json).name }}"
  when: terragrunt_version == 'latest'

- name: Linux | Use the specified Terragrunt version when latest var is not define
  set_fact:
    terragrunt_version_to_install: "{{ terragrunt_version }}"
  when: terragrunt_version != 'latest'

# This task avoids downloading terragrunt every time
- name: Linux | Check if terragrunt is present with the right version
  command: "{{ terragrunt_path }}/terragrunt --version"
  register: terragrunt_installed_version
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: Linux | Install terragrunt
  get_url:
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/{{ terragrunt_version_to_install }}/terragrunt_linux_{{ base_arch[ansible_architecture] | default('amd64') }}"
    dest: "{{ terragrunt_path }}terragrunt"
    mode: u+x,g+x,o+x
    force: yes
  when: terragrunt_version_to_install not in terragrunt_installed_version.stdout | default('empty')
